### ISSUE TITLE
Error during installation [make, fatal error: pqxx/pqxx: No such file or directory]

### ISSUE THREAD

**Issue by victoriasavi** [XAMPP/Celty#1]
[ 90%] Building CXX object modules/kishitani/CMakeFiles/kishitani.dir/kishitani.cc.o
    /opt/celty/modules/kishitani/kishitani.cc:5:21: fatal error: pqxx/pqxx: No such file or directory
     #include <pqxx/pqxx>
                     ^
    compilation terminated.
    make[2]: *** [modules/kishitani/CMakeFiles/kishitani.dir/kishitani.cc.o] Error 1
    make[1]: *** [modules/kishitani/CMakeFiles/kishitani.dir/all] Error 2
    make: *** [all] Error 2

Get the above error on 'make' on both Ubuntu Server 14.04 and Debian 8.2

**Comment by XAMPP** [comment]
Another note: The tracker itself is not quite functional quite yet, working on that.
